name: Lint code style issues

on:
  pull_request:

jobs:
  lint-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: fileinfo, exif, gd, pdo, sqlite, pdo_sqlite, intl

      - name: Pint Check
        uses: aglipanci/laravel-pint-action@1.0.0
        with:
          testMode: true
          verboseMode: true