name: Lint code style issues

on:
  pull_request:

jobs:
  lint-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: 8.4
          extensions: fileinfo, exif, gd, pdo, sqlite, pdo_sqlite, intl

      - name: Pint Check
        uses: aglipanci/laravel-pint-action@61f2bc4f4d5da076029d370fa2f268fd6b298041 # 2.3.1
        with:
          testMode: true
          verboseMode: true